%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) copyright 2021 Sepideh Shafiei (sepideh.shafiee@gmail.com), all rights reserved
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% In the process of pitch recognition, there are smalle intervals of unrecognized frequencies
% We have extrapolated those frequencies with linear regression, using the
% frequencies around them.

function[Y_centExtrapolated] = extrapolateZeros(Y_cent)

global GusheName;
Y_centExtrapolated=Y_cent;

%sometimes, zero extrapolations have problem if octave error causes
%Y_cent(e)-Y_cent(b-1)   ) < 500) to become false... so before
%octaveCorrections, we handle them here

if strncmp( GusheName, "D4_G35_M4_", 9)  % this was here for a while.. it may have effected other hand manipulations...
    Y_centExtrapolated ( Y_centExtrapolated >3680) = Y_centExtrapolated ( Y_centExtrapolated >3680) -1200; %davaami D4_G35 needs this
    Y_cent ( Y_cent >3680) = Y_cent ( Y_cent >3680) -1200; %davaami D4_G35 needs this
end
i=10;
gapSize= 35;
if  (strncmp('D4_G35_M4_A7_T3_firstB_2',   GusheName, 11) == true )
    gapSize= 11;
end
if  (strncmp('D13_G3_M1_A1_T1',   GusheName, 5) == true ) %D13_G
    gapSize= 18;
end
if  (strncmp('D13_G48_M1_A1_T1',   GusheName, 9) == true ) %D13_G48
    gapSize= 22;
end
if  (strncmp('D4_G32_M4_A7_T3_',   GusheName, 8) == true )
    gapSize= 18;
end
if  (strncmp('D6_G32_M4_A7_T3_',   GusheName, 4) == true )
    gapSize= 32;
end
if  (strncmp('D5_G3_M4_A7_T3_',   GusheName, 4) == true )
    gapSize= 18;
end
while (i< size(Y_cent,1)-8)   % was -10, caused problem for davaami D4_G35, changed to -8
    i=i+1;
    if ( Y_cent(i) == 0)
        b= i;
        while (Y_cent(i) == 0)
            i = i+1;
            if (i > (size(Y_cent,1)))
                break;
            end
        end
        if (i > (size(Y_cent,1)))
            e=i-1;
        else
            e = i;
        end
        
        if ( b > 11000  && b < 14000)
            fprintf("b = %d, e=%d  length=%d\n", b , e , e-b);
        end
        
        if ((abs(    Y_cent(e)-Y_cent(b-1)   ) < 500) && (e-b < gapSize) &&...
                (~((strcmp('D1_G154_M1_A1_T1_firstB_15 Shur_masnavi',        GusheName) == true ) && (b ==1563))) && ...
                (~((strcmp('D1_G5_M4_A7_T3_firstB_2 shur_DaraamadDovvomdavaami', GusheName) == true ) && (b ==631))) && ...
                (~((strcmp('D1_G17_M4_A7_T3_firstB_4 shur_DaraamadRahaavidavaami', GusheName) == true ) && (b ==56))) && ...
                (~((strcmp('D1_G17_M4_A7_T3_firstB_4 shur_DaraamadRahaavidavaami', GusheName) == true ) && (b ==160))) && ...
                (~((strcmp('D1_G17_M4_A7_T3_firstB_4 shur_DaraamadRahaavidavaami', GusheName) == true ) && (b ==872))) && ...
                (~((strcmp('D1_G17_M4_A7_T3_firstB_4 shur_DaraamadRahaavidavaami', GusheName) == true ) && (b ==1147))) && ...
                (~((strcmp('D1_G20_M4_A7_T3_firstB_3 shur_Kereshmehdavaami', GusheName) == true ) && (b ==1546))) && ...
                (~((strcmp('D1_G20_M4_A7_T3_firstB_3 shur_Kereshmehdavaami', GusheName) == true ) && (b ==2513))) && ...
                (~((strcmp('D1_G55_M4_A7_T3_firstB_5 shur_Salmakdavaami',   GusheName) == true ) && (b ==481))) && ...
                (~((strcmp('D1_G55_M4_A7_T3_firstB_5 shur_Salmakdavaami',   GusheName) == true ) && (b ==1500))) && ...
                (~((strcmp('D1_G55_M4_A7_T3_firstB_5 shur_Salmakdavaami',   GusheName) == true ) && (b ==2568))) && ...
                (~((strcmp('D1_G55_M4_A7_T3_lastC_5 shur_Salmakdavaami',   GusheName) == true ) && (b ==2568))) && ...
                (~((strcmp('D12_G13_M1_A1_T1_firstB_2 navaa_gardaniyeh',    GusheName) == true ) && (b ==15773))) && ...
                (~((strcmp('D12_G13_M1_A1_T1_firstB_2 navaa_gardaniyeh',    GusheName) == true ) && (b ==13726))) && ...
                (~((strcmp('D12_G13_M1_A1_T1_lastC_2 navaa_gardaniyeh',    GusheName) == true ) && (b ==15773))) && ...
                (~((strcmp('D12_G13_M1_A1_T1_lastC_2 navaa_gardaniyeh',    GusheName) == true ) && (b ==13726))) && ...
                (~((strcmp('D12_G13_M1_A1_T1_firstB_2 navaa_gardaniyeh',    GusheName) == true ) && (b ==10344))) && ...
                (~((strcmp('D12_G13_M1_A1_T1_lastC_2 navaa_gardaniyeh',    GusheName) == true ) && (b ==2689))) && ...
                (~((strcmp('D12_G13_M1_A1_T1_lastC_2 navaa_gardaniyeh',    GusheName) == true ) && (b ==10344))) && ...
                (~((strcmp('D12_G13_M1_A1_T1_firstB_2 navaa_gardaniyeh',    GusheName) == true ) && (b ==2689))) && ...
                (~((strcmp('D12_G23_M1_A1_T1_firstB_5 navaa_oshshaaq',    GusheName) == true ) && (b ==9051))) && ...
                (~((strcmp('D12_G23_M1_A1_T1_lastC_5 navaa_oshshaaq',    GusheName) == true ) && (b ==9051))) && ...
                (~((strcmp('D12_G42_M1_A1_T1_firstB_7 navaa_xojasteh',    GusheName) == true ) && (b ==14156))) && ...
                (~((strcmp('D12_G42_M1_A1_T1_lastC_7 navaa_xojasteh',    GusheName) == true ) && (b ==14156))) && ...
                (~((strcmp('D12_G51_M1_A1_T1_firstB_11 navaa_neyrizOgusheNeyriz',    GusheName) == true ) && (b ==19634))) && ...
                (~((strcmp('D12_G51_M1_A1_T1_lastC_11 navaa_neyrizOgusheNeyriz',    GusheName) == true ) && (b ==19634))) && ...
                (~((strcmp('D12_G58_M1_A1_T1_firstB_12 navaa_rohabOnaqus',       GusheName) == true ) && (b ==20078))) && ...
                (~((strcmp('D12_G58_M1_A1_T1_lastC_12 navaa_rohabOnaqus',       GusheName) == true ) && (b ==20078))) && ...
                (~((strcmp('D2_G49_M1_A1_T1_firstB_5 abuata_xosrow_shirin',           GusheName) == true ) && (b ==3019))) && ...
                (~((strcmp('D2_G65_M1_A1_T1_firstB_4 abuata_raamkali_ii',           GusheName) == true ) && (b ==4025))) && ...
                (~((strcmp('D2_G65_M1_A1_T1_firstB_4 abuata_raamkali_ii',           GusheName) == true ) && (b ==10714))) && ...
                (~((strcmp('D3_G32_M1_A1_T1_firstB_4 zand_ruholarvaah',           GusheName) == true ) && (b ==5507))) && ...
                (~((strcmp('D3_G32_M1_A1_T1_lastC_4 zand_ruholarvaah',           GusheName) == true ) && (b ==5507))) && ...
                (~((strcmp('D3_G28_M1_A1_T1_firstB_3 zand_dogaah',           GusheName) == true ) && (b ==4642))) && ...
                (~((strcmp('D3_G28_M1_A1_T1_lastC_3 zand_dogaah',           GusheName) == true ) && (b ==4642))) && ...
                (~((strcmp('D3_G38_M1_A1_T1_lastC_6 zand_feyli',           GusheName) == true ) && (b ==12810))) && ...
                (~((strcmp('D3_G38_M1_A1_T1_firstB_6 zand_feyli',           GusheName) == true ) && (b ==12810))) && ...
                (~((strcmp('D3_G64_M1_A1_T1_firstB_12 zand_masnavi',              GusheName) == true ) && (b ==11835))) && ...
                (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (b ==11835))) && ...
                (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (b ==18232))) && ...
                (~((strcmp('D4_G5_M4_A7_T3_firstB_1 afshaari_daraamaddavaami',    GusheName) == true ) && (b ==4808))) && ...
                (~((strcmp('D4_G5_M4_A7_T3_firstB_1 afshaari_daraamaddavaami',    GusheName) == true ) && (b ==4560))) && ...
                (~((strcmp('D4_G5_M4_A7_T3_firstB_1 afshaari_daraamaddavaami',    GusheName) == true ) && (b ==3745))) && ...
                (~((strcmp('D4_G5_M4_A7_T3_firstB_1 afshaari_daraamaddavaami',    GusheName) == true ) && (b ==3490))) && ...
                (~((strcmp('D4_G5_M4_A7_T3_firstB_1 afshaari_daraamaddavaami',    GusheName) == true ) && (b ==3595))) && ...
                (~((strcmp('D4_G5_M4_A7_T3_firstB_1 afshaari_daraamaddavaami',    GusheName) == true ) && (b ==3119))) && ...
                (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',    GusheName) == true ) && (b ==500))) && ...
                (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',    GusheName) == true ) && (b ==579))) && ...
                (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',    GusheName) == true ) && (b ==1613))) && ...
                (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',    GusheName) == true ) && (b ==1290))) && ...
                (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',    GusheName) == true ) && (b ==1144))) && ...
                (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',    GusheName) == true ) && (b ==921))) && ...
                (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',    GusheName) == true ) && (b ==1116))) && ...
                (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',    GusheName) == true ) && (b ==1812))) && ...
                (~((strcmp('D4_G32_M4_A7_T3_firstB_4 afshaari_qaraaiidavaami',    GusheName) == true ) && (b ==1192))) && ...
                (~((strcmp('D4_G32_M4_A7_T3_firstB_4 afshaari_qaraaiidavaami',    GusheName) == true ) && (b ==1449))) && ...
                (~((strcmp('D4_G32_M4_A7_T3_firstB_4 afshaari_qaraaiidavaami',    GusheName) == true ) && (b ==2518))) && ...
                (~((strcmp('D4_G32_M4_A7_T3_firstB_4 afshaari_qaraaiidavaami',    GusheName) == true ) && (b ==2987))) && ...
                (~((strcmp('D5_G50_M4_A7_T3_firstB_4 dashti_ghamAngizdavaami',    GusheName) == true ) && (b ==875))) && ...
                (~((strcmp('D5_G50_M4_A7_T3_firstB_4 dashti_ghamAngizdavaami',    GusheName) == true ) && (b ==971))) && ...
                (~((strcmp('D12_G62_M1_A1_T1_firstB_14 navaa_shahXataaii',    GusheName) == true ) && (b ==21322))) && ...
                (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',    GusheName) == true ) && (b ==21322))) && ...
                (~((strcmp('D13_G3_M1_A1_T1_firstB_1 rast5gaah_daraamad',    GusheName) == true ) && (b ==6269))) && ...
                (~((strcmp('D13_G44_M1_A1_T1_firstB_7 rast5gaah_oshaaq',    GusheName) == true ) && (b ==24020))) && ...
                (~((strcmp('D13_G48_M1_A1_T1_firstB_8 rast5gaah_bayaatAjam',GusheName) == true ) && (b ==19144))) && ...
                (~((strcmp('D13_G29_M1_A1_T1_firstB_4 rast5gaah_ruhafzaa',  GusheName) == true ) && (b ==2050))) && ...
                (~((strcmp('D13_G105_M1_A1_T1_firstB_14 rast5gaah_raakKeshmir',  GusheName) == true ) && (b ==3753))) && ...
                (~((strcmp('D2_G65_M1_A1_T1_firstB_4 abuata_raamkali_ii',        GusheName) == true ) && (b ==3638))) && ...
                (~((strcmp('D2_G52_M1_A1_T1_firstB_9 abuata_chahaarpaareh',        GusheName) == true ) && (b ==7476))) && ...
                (~((strcmp('D3_G48_M1_A1_T1_firstB_7 zand_shekasteh',       GusheName) == true ) && (b ==11963))) && ...
                (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',       GusheName) == true ) && (b ==11963))) && ...
                (~((strcmp('D3_G61_M1_A1_T1_firstB_11 zand_mehrabaani',     GusheName) == true ) && (b ==14547))) && ...
                (~((strcmp('D3_G61_M1_A1_T1_lastC_11 zand_mehrabaani',     GusheName) == true ) && (b ==14547))) && ...
                (~((strcmp('D6_G11_M4_A7_T3_firstB_3 bayaatKord_hazindavaami',    GusheName) == true ) && (b ==1564))) && ...
                (~((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',    GusheName) == true ) && (b ==4723))) && ...
                (~((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',    GusheName) == true ) && (b ==6186))) && ...
                (~((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',    GusheName) == true ) && (b ==14348))) && ...
                (~((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',    GusheName) == true ) && (b ==4790))) && ...
                (~((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',    GusheName) == true ) && (b ==5597))) && ...
                (~((strcmp('D6_G12_M4_A7_T3_firstB_3 bayaatKord_hazindavaami',    GusheName) == true ) && (b ==383))) && ...
                (~((strcmp('D6_G13_M4_A7_T3_firstB_4 bayaatKord_owjdavaami',    GusheName) == true ) && (b ==267))) && ...
                (~((strcmp('D6_G13_M4_A7_T3_firstB_4 bayaatKord_owjdavaami',    GusheName) == true ) && (b ==1697))) && ...
                (~((strcmp('D6_G13_M4_A7_T3_firstB_4 bayaatKord_owjdavaami',    GusheName) == true ) && (b ==2842))) && ...
                (~((strcmp('D8_G47_M4_A7_T3_firstB_5 homaayun_neydaavudDavaami',    GusheName) == true ) && (b ==12588))) && ...
                (~((strcmp('D8_G53_M4_A7_T3_firstB_8 homaayun_owjDavaami',    GusheName) == true ) && (b ==1965))) && ...
                (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',    GusheName) == true ) && (b == 7183))) && ...
                (~((strcmp('D9_G46_M1_A1_T1_firstB_5 bayaatEsfahaan_suzOgodaaz',    GusheName) == true ) && (b == 8167))) && ...
                (~((strcmp('D9_G57_M1_A1_T1_firstB_7 bayaatEsfahaan_naghmeh',    GusheName) == true ) && (b == 9144))) && ...
                (~((strcmp("D9_G59_M1_A1_T1_firstB_8 bayaatEsfahaan_gushehDarEsfahaan",     GusheName) == true ) && (b == 12678 ))) && ...
                (~((strcmp('D1_G111_M0_A12_T2_firstB_1 shur_razavi',                        GusheName) == true ) && (b == 1255  ))) &&...
                (~((strcmp('D1_G5_M0_A2_T2_firstB_1 shur_daraamad_Aazar',                       GusheName) == true ) && (b == 5775  ))) &&...
                (~((strcmp('D1_G5_M0_A2_T2_lastC_1 shur_daraamad_Aazar',                        GusheName) == true ) && (b == 5775  ))) &&...
                (~((strcmp('D1_G5_M0_A2_T2_firstB_1 shur_daraamad_Aazar',                       GusheName) == true ) && (b == 5777  ))) &&...
                (~((strcmp('D1_G5_M0_A2_T2_lastC_1 shur_daraamad_Aazar',                        GusheName) == true ) && (b == 5777  ))) &&...
                (~((strcmp('D1_G154_M1_A1_T1_lastC_15 Shur_masnavi',        GusheName) == true ) && (b ==1563))))  ...
                ||...
                (...
                ((strcmp('D2_G65_M1_A1_T1_firstB_4 abuata_raamkali_ii',                 GusheName) == true ) && (b ==3638000)) || ...
                ((strcmp('D6_G10_M4_A7_T3_firstB_1 bayaatKord_daraamadavvaldavaami',    GusheName) == true ) && (b ==5214)) ||...
                ((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',   GusheName) == true ) && (b ==6186)) || ...
                ((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',   GusheName) == true ) && (b ==13085)) || ...
                ((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',   GusheName) == true ) && (b ==16537)) || ...
                ((strcmp('D6_G10_M4_A7_T3_firstB_1 bayaatKord_daraamadavvaldavaami',    GusheName) == true ) && (b ==6644)) ...
                )
            
            
            for j=b:e
                Y_centExtrapolated(j) = Y_cent(b-1) + (Y_cent(e)-Y_cent(b-1))*(j-b)/(e-b);
            end
            
        end
        
    end
    
end
%(~((strcmp('D4_G35_M4_A7_T3_firstB_3 afshaari_araaqdavaami',    GusheName) == true ) && (b ==468))) && ...
%((strcmp('D1_G111_M0_A12_T2_firstB_1 shur_razavi',         GusheName) == true ) && (b ==538)) ||...

if  (strcmp('D2_G65_M1_A1_T1_firstB_4 abuata_raamkali_ii',   GusheName) == true )
    Y_centExtrapolated(487:515)   = 1850;
    Y_centExtrapolated(3027:3042) = 1800;
    Y_centExtrapolated(4025:4046) = 1800;
end

if  (strcmp('D2_G37_M1_A1_T1_firstB_8 abuata_hejaaz',   GusheName) == true )
    Y_centExtrapolated(42736:42742)   = 1550;
    Y_centExtrapolated(42551:42552)   = 0;
    
end
if  (strcmp('D2_G52_M1_A1_T1_firstB_9 abuata_chahaarpaareh',   GusheName) == true )
    
    Y_centExtrapolated(21608:21622)   = 0;
    
end

if  (strcmp('D1_G55_M4_A7_T3_firstB_5 shur_Salmakdavaami',   GusheName) == true )
    Y_centExtrapolated(4655:4674) = 0;
end

if  (strcmp('D4_G32_M4_A7_T3_firstB_4 afshaari_qaraaiidavaami',   GusheName) == true )
    Y_centExtrapolated(2445:2455) = 0;
end

if  (strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',   GusheName) == true )
    Y_centExtrapolated(9252:9284) = 2300;
    Y_centExtrapolated(10606:10637) = 2300;
    Y_centExtrapolated(11863:11896) = 2300;
end

if  (strcmp('D13_G105_M1_A1_T1_firstB_14 rast5gaah_raakKeshmir',   GusheName) == true )
    Y_centExtrapolated(3472:3508) = 3120;
end
if  (strcmp('D13_G26_M1_A1_T1_firstB_3 rast5gaah_naghme',   GusheName) == true )
    Y_centExtrapolated(2611:2651) = 2120;
end

if  (strcmp('D5_G50_M4_A7_T3_firstB_4 dashti_ghamAngizdavaami',   GusheName) == true )
    Y_centExtrapolated(7) = Y_centExtrapolated(6);
    Y_centExtrapolated(8) = Y_centExtrapolated(9);
end
end
