%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) copyright 2021 Sepideh Shafiei (sepideh.shafiee@gmail.com), all rights reserved
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function plotGenerator(Y_tahrir,Y_centOriginal,X,Y_audioShahed,Y1_solidAverage,Y_vibrato,Y_smooth,Y_spike,Y_spike1,audioPitchRecFilename)

figure5=figure;
plot(X,Y_audioShahed, 'Marker','.','Color', 'red',...
    'LineStyle', 'none');
hold on
Y_centOriginal(Y_centOriginal==0)=nan;
plot(X,Y_centOriginal,'Marker','.','MarkerSize',5, 'Color', 'k',...
    'LineStyle', 'none');
hold on
Y1_solidAverage2=Y1_solidAverage;
Y1_solidAverage2(Y1_solidAverage2==0)=nan;
plot(X,Y1_solidAverage2,'Marker','.','Color', 'g',...
    'LineStyle', 'none');
hold on
Y_vibrato2=Y_vibrato;
Y_vibrato2(Y_vibrato2==0)=nan;
plot(X,Y_vibrato2,'Marker','.','Color', 'green',...
    'LineStyle', 'none');
hold on
%{
sentenceBeginning(sentenceBeginning==0)=nan;
plot(X,sentenceBeginning, 'Marker','.','Color',[0.3010 0.7450 0.9330],...
        'LineStyle', 'none');
hold on
%}
plot ( X, Y_smooth , '--gs',...
    'LineWidth',1,...
    'Marker','.','MarkerSize',1,...
    'Color', [0.9290 0.6940 0.1250],...
    'LineStyle',':' );
hold on
plot ( X, Y_spike , '--gs',...
    'LineWidth',3,...
    'Marker','.','MarkerSize',3,...
    'Color', 'magenta',...
    'LineStyle',':' );
hold on
plot ( X, Y_spike1 , '--gs',...
    'LineWidth',2,...
    'Marker','.','MarkerSize',2,...
    'Color', 'cyan',...
    'LineStyle',':' );
hold on
plot ( X, Y_tahrir , '--gs',...
    'LineWidth',1,...
    'Marker','.','MarkerSize',5,...
    'Color', 'r',...
    'LineStyle', 'none');
title(strcat('Separated:',audioPitchRecFilename), 'interpreter', 'none')
end
