%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) copyright 2021 Sepideh Shafiei (sepideh.shafiee@gmail.com), all rights reserved
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function seg= splitPlot( y_cent,MidiFreq, ix, iy, fig, GusheName)

%global corrections;
% use SpikeFinder?

i=1;
while (y_cent(ix(i)) ==0 )  % skip over the  INITIAL ZEROS
    i=i+1;
end
j=1;
while ( i < size(ix,1) )
    seg(j).curveBeg =i;
    seg(j).curveEnd = -1;
    seg(j).zeroEnd  = -1;
    while ( y_cent(ix(i)) ~=0) && ~isnan(y_cent(ix(i) ))   % non-zeros
        if ( i < size(ix,1))
            i= i + 1;
        else
            break;
        end
    end
    if ( i >= size(ix, 1) )
        seg(j).curveEnd= size(ix,1);
        break;
    end
    
    seg(j).curveEnd = i;
    while (   ( y_cent(ix(i)) == 0) ||   isnan(y_cent(ix(i)) )   ) %zeros
        i = i + 1;
        if ( i > size(ix,1) )
            break;
        end
    end
    seg(j).zeroEnd = i;
    if seg(j).zeroEnd > size(ix,1)
        seg(j).zeroEnd = seg(j).zeroEnd -1;
    end
    j= j + 1;
end
for z=1:size(seg,2)
    fprintf("++segs aa:z=%d rawbegin=%d  dtw-beg= %d end=%d zero=  %d   (%d)\n", z, ...
        ix(seg(z).curveBeg),seg(z).curveBeg, seg(z).curveEnd, seg(z).zeroEnd  , seg(z).curveEnd - seg(z).curveBeg);
end
i=1;

while i < size (seg,2)      %small silences
    fprintf("\t\t i=%d, Beg end zero = %d  %d  %d \n", i, seg(i).curveBeg, seg(i).curveEnd, seg(i).zeroEnd);
    
    % connect the segments together if the distance is too small
    if (seg(i).zeroEnd-seg(i).curveEnd < 40) &&...
            (~((strcmp('D1_G5_M4_A7_T3_firstB_2 shur_DaraamadDovvomdavaami',    GusheName) == true ) && (i ==5))) &&...
            (~((strcmp('D4_G39_M1_A1_T1_lastC_5 afshaari_nahib',    GusheName) == true ) && (i ==5))) &&...
            (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami', GusheName) == true ) && (9 == 9)))    &&...
            (~((strcmp('D4_G26_M4_A7_T3_lastC_2 afshaari_jaamehdaraandavaami',  GusheName) == true ) && (9 == 9)))    &&...
            (~((strcmp('D6_G10_M4_A7_T3_firstB_1 bayaatKord_daraamadavvaldavaami',   GusheName) == true ) )) && ...
            (~((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',   GusheName) == true ) )) && ...
            (~((strcmp('D6_G12_M4_A7_T3_firstB_3 bayaatKord_hazindavaami',   GusheName) == true ) )) && ...
            (~((strcmp('D6_G13_M4_A7_T3_firstB_4 bayaatKord_owjdavaami',     GusheName) == true ) && (i ~=2))) && ...
            (~((strcmp('D5_G46_M4_A7_T3_firstB_2 dashti_dashtestaanidavaami',GusheName) == true )  )) && ...
            (~((strcmp('D5_G3_M4_A7_T3_firstB_1 dashti_daraamaddavaami',     GusheName) == true ) )) && ...
            (~((strcmp('D5_G50_M4_A7_T3_firstB_4 dashti_ghamAngizdavaami',     GusheName) == true ) )) && ...
            (~((strcmp('D4_G35_M4_A7_T3_firstB_3 afshaari_araaqdavaami',     GusheName) == true ) &&...
            ((seg(i).curveEnd <600 )|| (seg(i).curveEnd>750 )) )) && ...
            (~((strcmp('D4_G32_M4_A7_T3_firstB_4 afshaari_qaraaiidavaami',     GusheName) == true ) &&...
            ((seg(i).curveEnd <10000 )|| (seg(i).curveEnd>12200 )) )) && ...
            (~((strcmp('D4_G39_M1_A1_T1_lastC_5 afshaari_nahib',    GusheName) == true ) && (i ==5))) &&...
            (~((strcmp('D1_G154_M1_A1_T1_firstB_15 Shur_masnavi',   GusheName) == true ) && (i ==2))) &&...
            (~((strcmp('D3_G28_M1_A1_T1_lastC_3 zand_dogaah',   GusheName) == true ) && (i ==6))) &&...
            (~((strcmp('D3_G28_M1_A1_T1_lastC_3 zand_dogaah',   GusheName) == true ) && (i ==9))) &&...
            (~((strcmp('D3_G32_M1_A1_T1_lastC_4 zand_ruholarvaah',   GusheName) == true ) && (i ==4))) &&...
            (~((strcmp('D3_G32_M1_A1_T1_lastC_4 zand_ruholarvaah',   GusheName) == true ) && (i ==10))) &&...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==99 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==13 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D3_G27_M1_A1_T1_lastC_5 zand_jaamedaraan',   GusheName) == true ) && (i==4))) &&...
            (~((strcmp('D3_G27_M1_A1_T1_lastC_5 zand_jaamedaraan',   GusheName) == true ) && (i==5))) &&...
            (~((strcmp('D3_G27_M1_A1_T1_lastC_5 zand_jaamedaraan',   GusheName) == true ) && (seg(i).curveEnd == 5646))) &&...
            (~((strcmp('D3_G61_M1_A1_T1_lastC_11 zand_mehrabaani',   GusheName) == true ) && (i ==3))) &&...
            (~((strcmp('D3_G61_M1_A1_T1_lastC_11 zand_mehrabaani',   GusheName) == true ) && (i ==6))) &&...
            (~((strcmp('D3_G61_M1_A1_T1_lastC_11 zand_mehrabaani',   GusheName) == true ) && (i ==8))) &&...
            (~((strcmp('D3_G61_M1_A1_T1_lastC_11 zand_mehrabaani',   GusheName) == true ) && (i ==9))) &&...
            (~((strcmp('D3_G38_M1_A1_T1_firstB_6 zand_feyli',                GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_lastC_6 zand_feyli',                 GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_firstB_6 zand_feyli',                GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_lastC_6 zand_feyli',                 GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_firstB_6 zand_feyli',                GusheName) == true ) && (i ==9 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_lastC_6 zand_feyli',                 GusheName) == true ) && (i ==9 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==17 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==23 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==24 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==32 ))) && ...
            (~((strcmp('D8_G37_M1_A1_T1_lastC_7 homaayun_bidaad',            GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D12_G15_M1_A1_T1_lastC_3 navaa_naghmeh',             GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D2_G52_M1_A1_T1_firstB_9 abuata_chahaarpaareh',      GusheName) == true ) && (i ==23 ))) &&...
            (~((strcmp('D1_G154_M1_A1_T1_lastC_15 Shur_masnavi',    GusheName) == true ) && (i ==2)))
        
        fprintf("++splitPlot:  small seg: diff2=%d  segs=%d\n", 0-seg(i).curveEnd+seg(i).zeroEnd , size(seg,2));
        fprintf("\t\t\t\t\t i=%d, Beg end zero = %d  %d  %d ----and-----", i, seg(i).curveBeg, seg(i).curveEnd, seg(i).zeroEnd);
        fprintf(" i=%d, Beg end zero = %d  %d  %d \n", i+1, seg(i+1).curveBeg, seg(i+1).curveEnd, seg(i+1).zeroEnd);
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd  = seg(i+1).zeroEnd;
        seg = [seg(1:i) seg(i+2:end) ];
        
    elseif ((strcmp('D3_G61_M1_A1_T1_lastC_11 zand_mehrabaani',  GusheName) == true ) && ...
            (    (seg(i).curveEnd < 1300) || (seg(i).curveEnd >2500 && seg(i).curveEnd < 3000)     ))
        fprintf(" inside if         i=%d seg end ========from end=%d to end=%d\n",i,  seg(i).curveEnd,  seg(i+1).curveEnd );
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd  = seg(i+1).zeroEnd;
        seg = [seg(1:i) seg(i+2:end) ];
    else
        i = i + 1;
    end
    
    if ((strcmp('D13_G60_M1_A1_T1_firstB_9 rast5gaah_nahibMohayyer',  GusheName) == true ) && ...
            ( seg(i).curveEnd > 33000) && ( seg(i).curveEnd < 34200))
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd  = seg(i+1).zeroEnd;
        seg = [seg(1:i) seg(i+2:end) ];
    end
    
    if ((strcmp('D13_G60_M1_A1_T1_firstB_9 rast5gaah_nahibMohayyer',  GusheName) == true ) && ...
            ( seg(i).curveEnd > 33000) && ( seg(i).curveEnd < 34200))
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd  = seg(i+1).zeroEnd;
        seg = [seg(1:i) seg(i+2:end) ];
    end
    
    if (    (strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',  GusheName) == true ) && ...
            ( ( seg(i).curveEnd > 10900) && ( seg(i).curveEnd < 10950)     || (i == 6))               )
        fprintf("begin = %d, moving end from=%d  to %d\n", seg(i).curveBeg, seg(i).curveEnd, seg(i+1).curveEnd)
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd  = seg(i+1).zeroEnd;
        seg = [seg(1:i) seg(i+2:end) ];
    end
    
    
    if ((strcmp('D3_G61_M1_A1_T1_firstB_11 zand_mehrabaani',  GusheName) == true ) && ...
            ((i==999) || (i==2))   )
        fprintf("connecting i=%d end=%d  ---> %d\n", i, seg(i).curveEnd,  seg(i+1).curveEnd)
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd  = seg(i+1).zeroEnd;
        seg = [seg(1:i) seg(i+2:end) ];
    end
    
    
    if ((strcmp('D8_G10_M1_A1_T1_lastC_1 homaayun_daraamad',  GusheName) == true ) && ...
            (seg(i-1).curveEnd >= 15300 ) && (seg(i-1).curveEnd < 15700 ) ...
            )
        i = i-1;
        fprintf("--->splitPlot:  small seg: diff2=%d  segs=%d\n", 0-seg(i).curveEnd+seg(i).zeroEnd , size(seg,2));
        fprintf("\t\t\t\t\t i=%d, Beg end zero = %d  %d  %d ----and-----", i, seg(i).curveBeg, seg(i).curveEnd, seg(i).zeroEnd);
        fprintf(" i=%d, Beg end zero = %d  %d  %d \n", i+1, seg(i+1).curveBeg, seg(i+1).curveEnd, seg(i+1).zeroEnd);
        
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd  = seg(i+1).zeroEnd;
        seg = [seg(1:i) seg(i+2:end) ];
    end
    
    
    fprintf("i=%d seg end =========%d\n",i,  seg(i).curveEnd );
    
    
end

for z=1:size(seg,2)
    fprintf("++segs A:z=%d rawbegin=%d  dtw-beg= %d end=%d zero=  %d   (%d)\n", z, ...
        ix(seg(z).curveBeg),seg(z).curveBeg, seg(z).curveEnd, seg(z).zeroEnd ,seg(z).curveEnd - seg(z).curveBeg)    ;
end

i=1;
doIt=0;
notYet = 1000;
while i < size (seg,2)   % get rid of small segments
    %the following few lines is a patch to make firstB and lastC the same
    %number of parts, by forcing two parts to be joint.
    fprintf("++splitplot: i=%d\n", i);
    if    ((strcmp('D11_G6_M1_A1_T1_firstB_1 Chahaargaah_daraamad',           GusheName) == true ) && (i ==4))  ||...
            ((strcmp('D12_G51_M1_A1_T1_firstB_11 navaa_neyrizOgusheNeyriz',   GusheName) == true ) && (i ==17)) ||...
            ((strcmp('D12_G51_M1_A1_T1_lastC_11 navaa_neyrizOgusheNeyriz',   GusheName) == true ) && (i ==17)) ||...
            ((strcmp('D2_G52_M1_A1_T1_firstB_9 abuata_chahaarpaareh',         GusheName) == true ) && (i ==17)) ||...
            ((strcmp('D4_G5_M1_A1_T1_firstB_1 afshaari_daraamad',  GusheName) == true ) && (i ==6))  ||...
            ((strcmp('D4_G5_M1_A1_T1_lastC_1 afshaari_daraamad',   GusheName) == true ) && (i ==6))  ||...
            ((strcmp('D4_G5_M1_A1_T1_lastC_1 afshaari_daraamad',   GusheName) == true ) && (i ==13)) ||...
            ((strcmp('D4_G5_M1_A1_T1_firstB_1 afshaari_daraamad',  GusheName) == true ) && (i ==13)) ||...
            ((strcmp('D4_G5_M1_A1_T1_firstB_1 afshaari_daraamad',  GusheName) == true ) && (i ==14)) ||...
            ((strcmp('D4_G5_M1_A1_T1_firstB_1 afshaari_daraamad',  GusheName) == true ) && (i ==16)) ||...
            ((strcmp('D4_G5_M1_A1_T1_lastC_1 afshaari_daraamad',   GusheName) == true ) && (i ==16)) ||...
            ((strcmp('D4_G5_M1_A1_T1_firstB_1 afshaari_daraamadx', GusheName) == true ) && (i ==19)) ||...
            ((strcmp('D3_G999_firstB_2 az',                        GusheName) == true ) && (i ==2))  ||...
            ((strcmp('D3_G999_lastC_2 az',                         GusheName) == true ) && (i ==2))  ||...
            ((strcmp('D3_G61_M1_A1_T1_firstB_11 zand_mehrabaani',  GusheName) == true ) && (i ==1))  ||...
            ((strcmp('D3_G61_M1_A1_T1_firstB_11 zand_mehrabaani',  GusheName) == true ) && (i ==2))  ||...
            ((strcmp('D3_G61_M1_A1_T1_lastC_11 zand_mehrabaani',   GusheName) == true ) && (i ==1))  ||...
            ((strcmp('D3_G61_M1_A1_T1_lastC_11 zand_mehrabaani',   GusheName) == true ) && (i ==3))  ||...
            ((strcmp('D3_G61_M1_A1_T1_firstB_11 zand_mehrabaani',   GusheName) == true ) && (i ==3))  ||...
            ((strcmp('D3_G61_M1_A1_T1_firstB_11 zand_mehrabaani',   GusheName) == true ) && (i ==9))  ||...
            ((strcmp('D11_G6_M1_A1_T1_firstB_1 Chahaargaah_daraamad', GusheName) == true ) && (i ==25))||...
            ((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==18)) ||...
            ((strcmp('D4_G57_M1_A1_T1_lastC_9 afshaari_masnavi',  GusheName) == true ) && (i ==18)) ||...
            ((strcmp('D8_G10_M1_A1_T1_firstB_1 homaayun_daraamad',GusheName) == true ) && (i ==11 )) || ...
            ((strcmp('D8_G63_M1_A1_T1_lastC_5 homaayun_tarz',               GusheName) == true ) && (i ==5 )) || ...
            ((strcmp("D8_G103_M1_A1_T1_firstB_12 homaayun_baxtiaariMo'alef", GusheName) == true ) && (i ==7  )) || ...
            ((strcmp("D8_G103_M1_A1_T1_lastC_12 homaayun_baxtiaariMo'alef", GusheName) == true ) && (i ==7  )) || ...
            ((strcmp("D8_G109_M1_A1_T1_firstB_9 homaayun_raazOniaaz_i",     GusheName) == true ) && (i ==3 )) || ...
            ((strcmp("D8_G109_M1_A1_T1_lastC_9 homaayun_raazOniaaz_i",      GusheName) == true ) && (i ==3 )) || ...
            ((strcmp("D9_G57_M1_A1_T1_firstB_7 bayaatEsfahaan_naghmeh",     GusheName) == true ) && (i ==3 )) || ...
            ((strcmp("D9_G57_M1_A1_T1_lastC_7 bayaatEsfahaan_naghmeh",     GusheName) == true ) && (i ==3 )) || ...
            ((strcmp("D9_G66_M1_A1_T1_firstB_11 bayaatEsfahaan_sufinaameh", GusheName) == true ) && (i ==28 )) || ...
            ((strcmp("D9_G66_M1_A1_T1_firstB_11 bayaatEsfahaan_sufinaameh", GusheName) == true ) && (i ==35 )) || ...
            ((strcmp("D10_G44_M1_A1_T1_firstB_6 segaah_hesaar",              GusheName) == true ) && (i ==4 )) || ...
            ((strcmp('D13_G80_M1_A1_T1_firstB_10 rast5gaah_tarz',         GusheName) == true ) && (i ==1 )) || ...
            ((strcmp('D13_G80_M1_A1_T1_firstB_10 rast5gaah_tarz',         GusheName) == true ) && (i ==11 )) || ...
            ((strcmp('D13_G80_M1_A1_T1_firstB_10 rast5gaah_tarz',         GusheName) == true ) && (i ==14 )) || ...
            ((strcmp('D13_G32_M1_A1_T1_firstB_5 rast5gaah_neyriz',         GusheName) == true ) && (i ==1 )) || ...
            ((strcmp('D13_G32_M1_A1_T1_firstB_5 rast5gaah_neyriz',         GusheName) == true ) && (i ==3 )) || ...
            ((strcmp('D13_G32_M1_A1_T1_firstB_5 rast5gaah_neyriz',         GusheName) == true ) && (i ==9 )) || ...
            ((strcmp('D13_G44_M1_A1_T1_firstB_7 rast5gaah_oshaaq',         GusheName) == true ) && (i ==19)) || ...
            ((strcmp('D13_G60_M1_A1_T1_firstB_9 rast5gaah_nahibMohayyer',      GusheName) == true ) && (i ==22 )) || ...
            ((strcmp('D13_G60_M1_A1_T1_firstB_9 rast5gaah_nahibMohayyer',      GusheName) == true ) && (i ==29 )) || ...
            ((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',     GusheName) == true ) && (i ==18 )) || ...
            ((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',     GusheName) == true ) && (i ==21 )) || ...
            ((strcmp('D6_G12_M4_A7_T3_firstB_3 bayaatKord_hazindavaami',     GusheName) == true ) && (i ==3 )) || ...
            ((strcmp('D4_G35_M4_A7_T3_firstB_3 afshaari_araaqdavaami',     GusheName) == true ) && (i ==3 )) || ...
            ((strcmp('D6_G13_M4_A7_T3_firstB_4 bayaatKord_owjdavaami',     GusheName) == true ) && (i ==4 )) || ...
            ((strcmp('D6_G13_M4_A7_T3_firstB_4 bayaatKord_owjdavaami',     GusheName) == true ) && (i ==10 )) || ...
            ((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==21 )) ||...
            ((strcmp('D4_G56_M1_A1_T1_firstB_8 afshaari_sadri',   GusheName) == true ) && (i ==5  )) ||...
            ((strcmp('D4_G56_M1_A1_T1_firstB_8 afshaari_sadri',   GusheName) == true ) && (i ==3  )) ||...
            ((strcmp('D1_G55_M0_A23_T2_firstB_1 shur_salmak',     GusheName) == true) &&  (i ==2  )) || ...
            ((strcmp('D1_G5_M0_A2_T2_firstB_1 shur_daraamad_Aazar',GusheName) == true ) && (i ==1 )) ||...
            ((strcmp('D1_G5_M0_A2_T2_lastC_1 shur_daraamad_Aazar', GusheName) == true ) && (i ==1 )) ||...
            ((strcmp('D1_G5_M0_A2_T2_firstB_1 shur_daraamad_Aazar',GusheName) == true ) && (i ==2 )) ||...
            ((strcmp('D1_G5_M0_A14_T2_firstB_1 shur_daraamad_Banaan', GusheName) == true ) && (i ==2 )) ||...
            ((strcmp('D1_G5_M0_A14_T2_lastC_1 shur_daraamad_Banaan', GusheName) == true ) && (i ==2 )) ||...
            ((strcmp('D4_G56_M1_A1_T1_lastC_8 afshaari_sadri',    GusheName) == true ) && (i ==3  )) ...
            
        fprintf("++splitPlot: compare correct: *****************force joint= %s %d\n", GusheName, i);
        if ( doIt == 4)  % if joint, i does not change! so, the next time do not do it.
            doIt = 0;
        else
            doIt= 4;
        end
    else
        doIt=0;
    end
    
    
    fprintf("++splitPlotK: is it short/etc?? i=%d %d %d %d  (%D)\n",i,...
        seg(i).curveBeg, seg(i).curveEnd, seg(i).zeroEnd,    seg(i).curveEnd -seg(i).curveBeg  );
    
    inc =1;
    if (    ...
            ((seg(i).curveEnd-seg(i).curveBeg < 600)  && (seg(i).zeroEnd-seg(i).curveEnd < 150) ) ||...
            (seg(i).curveEnd-seg(i).curveBeg < 50)  ...
            ) &&...
            (...
            (~((strcmp('D1_G5_M4_A7_T3_firstB_2 shur_DaraamadDovvomdavaami', GusheName) == true ) )) && ...
            (~((strcmp('D1_G5_M0_A2_T2_lastC_1 shur_daraamad_Aazar',         GusheName) == true ) && (i ==3 ))) &&...
            (~((strcmp('D4_G35_M4_A7_T3_firstB_3 afshaari_araaqdavaami',     GusheName) == true ) )) && ...
            (~((strcmp('D4_G32_M4_A7_T3_firstB_4 afshaari_qaraaiidavaami',     GusheName) == true ) )) && ...
            (~((strcmp('D1_G7_M4_A7_T3_firstB_1 shur_daraamdXaaraadavaami',   GusheName) == true ) )) && ...
            (~((strcmp('D6_G10_M4_A7_T3_firstB_1 bayaatKord_daraamadavvaldavaami',   GusheName) == true ) )) && ...
            (~((strcmp('D6_G11_M4_A7_T3_firstB_2 bayaatKord_daraamadDovvomdavaami',   GusheName) == true ) )) && ...
            (~((strcmp('D6_G12_M4_A7_T3_firstB_3 bayaatKord_hazindavaami', GusheName) == true ) )) && ...
            (~((strcmp('D6_G13_M4_A7_T3_firstB_4 bayaatKord_owjdavaami',   GusheName) == true )  && (i ~=6) )) && ...
            (~((strcmp('D1_G20_M4_A7_T3_firstB_3 shur_Kereshmehdavaami',   GusheName) == true ) && (i ==3 +notYet))) && ...
            (~((strcmp('D1_G20_M4_A7_T3_firstB_3 shur_Kereshmehdavaami',   GusheName) == true ) && (i ==4))) && ...
            (~((strcmp('D1_G20_M4_A7_T3_firstB_3 shur_Kereshmehdavaami',   GusheName) == true ) && (i ==5))) && ...
            (~((strcmp('D1_G55_M4_A7_T3_firstB_5 shur_Salmakdavaami',      GusheName) == true ) && (i ==3))) && ...
            (~((strcmp('D1_G55_M4_A7_T3_firstB_5 shur_Salmakdavaami',      GusheName) == true )   && (i ==5))) && ...
            (~((strcmp('D5_G46_M4_A7_T3_firstB_2 dashti_dashtestaanidavaami',GusheName) == true ) && (3 ==3 ))) && ...
            (~((strcmp('D5_G3_M4_A7_T3_firstB_1 dashti_daraamaddavaami',     GusheName) == true ) && (3 ==3 ))) && ...
            (~((strcmp('D5_G50_M4_A7_T3_firstB_4 dashti_ghamAngizdavaami',     GusheName) == true ) && (3 ==3 ))) && ...
            (~((strcmp('D8_G47_M4_A7_T3_firstB_5 homaayun_neydaavudDavaami',     GusheName) == true ) && (3 ==3 ))) && ...
            (~((strcmp('D8_G37_M4_A7_T3_firstB_6 homaayun_bidaadDavaami',     GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D8_G37_M4_A7_T3_firstB_6 homaayun_bidaadDavaami',     GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D8_G53_M4_A7_T3_firstB_8 homaayun_owjDavaami',     GusheName) == true ) && (i ==4 ))) && ...
            (~((strcmp('D8_G53_M4_A7_T3_firstB_8 homaayun_owjDavaami',     GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D8_G53_M4_A7_T3_firstB_8 homaayun_owjDavaami',     GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==18 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==19 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==22 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==23 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==25 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==26 ))) && ...
            (~((strcmp('D8_G103_M4_A7_T3_firstB_7 homaayun_baxtiariDavaami',  GusheName) == true ) && (i ==27 ))) && ...
            (~((strcmp('D3_G14_M1_A1_T1_firstB_2 zand_daraamadII',            GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D8_G10_M1_A1_T1_lastC_1 homaayun_daraamad',           GusheName) == true ) && (i ==11 ))) && ...
            (~((strcmp('D8_G10_M1_A1_T1_lastC_1 homaayun_daraamad',           GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D8_G10_M1_A1_T1_lastC_1 homaayun_daraamad',           GusheName) == true ) && (i ==16 ))) && ...
            (~((strcmp('D8_G10_M1_A1_T1_firstB_1 homaayun_daraamad',          GusheName) == true ) && (i ==15 ))) && ...
            (~((strcmp('D8_G10_M1_A1_T1_lastC_1 homaayun_daraamad',           GusheName) == true ) && (i ==15 ))) && ...
            (~((strcmp('D8_G10_M1_A1_T1_firstB_1 homaayun_daraamad',           GusheName) == true ) && (i ==23 ))) && ...
            (~((strcmp('D8_G10_M1_A1_T1_lastC_1 homaayun_daraamad',           GusheName) == true ) && (i ==23 ))) && ...
            (~((strcmp('D8_G63_M1_A1_T1_firstB_5 homaayun_tarz',              GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D8_G63_M1_A1_T1_lastC_5 homaayun_tarz',              GusheName) == true ) && (i ==14 ))) && ...
            (~((strcmp('D8_G63_M1_A1_T1_firstB_5 homaayun_tarz',              GusheName) == true ) && (i ==14 ))) && ...
            (~((strcmp('D8_G63_M1_A1_T1_lastC_5 homaayun_tarz',              GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D8_G37_M1_A1_T1_firstB_7 homaayun_bidaad',             GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D8_G37_M1_A1_T1_lastC_7 homaayun_bidaad',             GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D8_G37_M1_A1_T1_firstB_7 homaayun_bidaad',             GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D8_G37_M1_A1_T1_lastC_7 homaayun_bidaad',             GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D8_G47_M1_A1_T1_firstB_6 homaayun_neydaavud',          GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D8_G47_M1_A1_T1_firstB_6 homaayun_neydaavud',          GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D8_G47_M1_A1_T1_lastC_6 homaayun_neydaavud',          GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D8_G47_M1_A1_T1_lastC_6 homaayun_neydaavud',          GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D8_G47_M1_A1_T1_lastC_6 homaayun_neydaavud',          GusheName) == true ) && (i ==11 ))) && ...
            (~((strcmp('D8_G49_M1_A1_T1_firstB_8 homaayun_raaje',              GusheName) == true ) && (i ==17 ))) && ...
            (~((strcmp('D8_G49_M1_A1_T1_lastC_8 homaayun_raaje',              GusheName) == true ) && (i ==17 ))) && ...
            (~((strcmp('D8_G62_M1_A1_T1_firstB_3 homaayun_leyliOmajnun',             GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D8_G62_M1_A1_T1_lastC_3 homaayun_leyliOmajnun',              GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D8_G62_M1_A1_T1_lastC_3 homaayun_leyliOmajnun',              GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D8_G85_M1_A1_T1_firsB_4 homaayun_shushtari',              GusheName) == true ) && (i ==13 ))) && ...
            (~((strcmp('D8_G85_M1_A1_T1_firsB_4 homaayun_shushtari',              GusheName) == true ) && (i ==14 ))) && ...
            (~((strcmp('D8_G85_M1_A1_T1_firsB_4 homaayun_shushtari',              GusheName) == true ) && (i ==15 ))) && ...
            (~((strcmp('D8_G85_M1_A1_T1_lastC_4 homaayun_shushtari',              GusheName) == true ) && (i ==13 ))) && ...
            (~((strcmp('D8_G85_M1_A1_T1_lastC_4 homaayun_shushtari',              GusheName) == true ) && (i ==14 ))) && ...
            (~((strcmp('D8_G85_M1_A1_T1_lastC_4 homaayun_shushtari',              GusheName) == true ) && (i ==15 ))) && ...
            (~((strcmp("D8_G103_M1_A1_T1_firstB_12 homaayun_baxtiaariMo'alef",    GusheName) == true ) && (i ==3 ))) && ...
            (~((strcmp("D8_G103_M1_A1_T1_lastC_12 homaayun_baxtiaariMo'alef",    GusheName) == true ) && (i ==3 ))) && ...
            (~((strcmp("D8_G103_M1_A1_T1_firstB_12 homaayun_baxtiaariMo'alef",    GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp("D8_G103_M1_A1_T1_lastC_12 homaayun_baxtiaariMo'alef",    GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp("D8_G109_M1_A1_T1_firstB_9 homaayun_raazOniaaz_i",       GusheName) == true ) && (i ==16 ))) && ...
            (~((strcmp("D8_G109_M1_A1_T1_lastC_9 homaayun_raazOniaaz_i",       GusheName) == true ) && (i ==16 ))) && ...
            (~((strcmp("D8_G109_M1_A1_T1_lastC_9 homaayun_raazOniaaz_i",       GusheName) == true ) && (i ==15 ))) && ...
            (~((strcmp("D8_G110_M1_A1_T1_firstB_10 homaayun_raazOniaaz_ii",       GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp("D8_G110_M1_A1_T1_lastC_10 homaayun_raazOniaaz_ii",        GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp("D8_G111_M1_A1_T1_firstB_11 homaayun_shushtari_ii",    GusheName) == true ) && (i ==20 ))) && ...
            (~((strcmp("D8_G111_M1_A1_T1_lastC_11 homaayun_shushtari_ii",     GusheName) == true ) && (i ==20 ))) && ...
            (~((strcmp("D8_G111_M1_A1_T1_firstB_11 homaayun_shushtari_ii",    GusheName) == true ) && (i ==21 ))) && ...
            (~((strcmp("D8_G111_M1_A1_T1_lastC_11 homaayun_shushtari_ii",     GusheName) == true ) && (i ==21 ))) && ...
            (~((strcmp("D9_G57_M1_A1_T1_firstB_7 bayaatEsfahaan_naghmeh",     GusheName) == true ) && (i ==3 ))) && ...
            (~((strcmp("D9_G46_M1_A1_T1_firstB_5 bayaatEsfahaan_suzOgodaaz",     GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp("D9_G46_M1_A1_T1_firstB_5 bayaatEsfahaan_suzOgodaaz",     GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp("D9_G59_M1_A1_T1_firstB_8 bayaatEsfahaan_gushehDarEsfahaan",     GusheName) == true ) && (i ==4 ))) && ...
            (~((strcmp("D9_G59_M1_A1_T1_firstB_8 bayaatEsfahaan_gushehDarEsfahaan",     GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp("D9_G59_M1_A1_T1_firstB_8 bayaatEsfahaan_gushehDarEsfahaan",     GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp("D9_G59_M1_A1_T1_firstB_8 bayaatEsfahaan_gushehDarEsfahaan",     GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp("D9_G60_M1_A1_T1_firstB_9 bayaatEsfahaan_bayaatShiraaz",     GusheName) == true ) && (i ==2 ))) && ...
            (~((strcmp("D9_G60_M1_A1_T1_lastC_9 bayaatEsfahaan_bayaatShiraaz",      GusheName) == true ) && (i ==2 ))) && ...
            (~((strcmp("D9_G60_M1_A1_T1_firstB_9 bayaatEsfahaan_bayaatShiraaz",     GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp("D9_G60_M1_A1_T1_lastC_9 bayaatEsfahaan_bayaatShiraaz",      GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp("D9_G65_M1_A1_T1_firstB_10 bayaatEsfahaan_masnavi",   GusheName) == true ) && (i ==4 ))) && ...
            (~((strcmp("D10_G8_M1_A1_T1_firstB_2 segaah_daraamadNoeDigar",   GusheName) == true ) && (i ==16 ))) && ...
            (~((strcmp("D10_G8_M1_A1_T1_firstB_2 segaah_daraamadNoeDigar",   GusheName) == true ) && (i ==21 ))) && ...
            (~((strcmp("D10_G26_M1_A1_T1_firstB_3 segaah_zabol",             GusheName) == true ) && (i ==9  ))) && ...
            (~((strcmp("D10_G78_M1_A1_T1_firstB_8 segaah_moxaalefBeMaghlub", GusheName) == true ) && (i ==4  ))) && ...
            (~((strcmp("D10_G78_M1_A1_T1_firstB_8 segaah_moxaalefBeMaghlub", GusheName) == true ) && (i ==9  ))) && ...
            (~((strcmp('D2_G6_M1_A1_T1_firstB_1 abuata_daraamad',            GusheName) == true ) && (i ==20 ))) &&...
            (~((strcmp('D2_G49_M1_A1_T1_firstB_5 abuata_xosrow_shirin',      GusheName) == true ) && (i ==4  ))) && ...
            (~((strcmp('D2_G51_M1_A1_T1_firstB_6 abuata_xosrow_shirin_ii',   GusheName) == true ) && (i ==14 ))) && ...
            (~((strcmp('D2_G51_M1_A1_T1_firstB_6 abuata_xosrow_shirin_ii',   GusheName) == true ) && (i ==15 ))) && ...
            (~((strcmp('D2_G52_M1_A1_T1_firstB_9 abuata_chahaarpaareh',      GusheName) == true ) && (i ==21 ))) &&...
            (~((strcmp('D2_G37_M1_A1_T1_firstB_8 abuata_hejaaz',             GusheName) == true ) && (i ==13 ))) && ...
            (~((strcmp('D2_G37_M1_A1_T1_firstB_8 abuata_hejaaz',             GusheName) == true ) && (i ==31 ))) && ...
            (~((strcmp('D2_G37_M1_A1_T1_firstB_8 abuata_hejaaz',             GusheName) == true ) && (i ==41 ))) && ...
            (~((strcmp('D2_G58_M1_A1_T1_firstB_7 abuata_gabri',              GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D2_G65_M1_A1_T1_firstB_4 abuata_raamkali_ii',        GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D3_G28_M1_A1_T1_firstB_3 zand_dogaah',               GusheName) == true ) && (i ==3 ))) && ...
            (~((strcmp('D3_G28_M1_A1_T1_firstB_3 zand_dogaah',               GusheName) == true ) && (i ==4 ))) && ...
            (~((strcmp('D3_G28_M1_A1_T1_firstB_3 zand_dogaah',               GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D3_G28_M1_A1_T1_lastC_3 zand_dogaah',                GusheName) == true ) && (i ==3 ))) && ...
            (~((strcmp('D3_G28_M1_A1_T1_lastC_3 zand_dogaah',                GusheName) == true ) && (i ==4 ))) && ...
            (~((strcmp('D3_G28_M1_A1_T1_lastC_3 zand_dogaah',                GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D3_G32_M1_A1_T1_firstB_4 zand_ruholarvaah',          GusheName) == true ) && (5 ==5 ))) && ...
            (~((strcmp('D3_G32_M1_A1_T1_lastC_4 zand_ruholarvaah',           GusheName) == true ) && (5 ==5 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_firstB_6 zand_feyli',                GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_lastC_6 zand_feyli',                 GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_firstB_6 zand_feyli',                GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_lastC_6 zand_feyli',                 GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_firstB_6 zand_feyli',                GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D3_G38_M1_A1_T1_lastC_6 zand_feyli',                 GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_firstB_7 zand_shekasteh',            GusheName) == true ) && (8 ==8 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D3_G48_M1_A1_T1_lastC_7 zand_shekasteh',             GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_firstB_12 zand_masnavi',             GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==16 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==13 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_firstB_12 zand_masnavi',              GusheName) == true ) && (i ==13 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_firstB_12 zand_masnavi',              GusheName) == true ) && (i ==19 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==28 ))) && ...
            (~((strcmp('D3_G64_M1_A1_T1_lastC_12 zand_masnavi',              GusheName) == true ) && (i ==29 ))) && ...
            (~((strcmp('D12_G3_M1_A1_T1_lastC_1 navaa_daraamad',            GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D12_G13_M1_A1_T1_firstB_2 navaa_gardaniyeh',        GusheName) == true ) && (i ==2 ))) && ...
            (~((strcmp('D12_G13_M1_A1_T1_lastC_2 navaa_gardaniyeh',        GusheName) == true ) && (i ==2 ))) && ...
            (~((strcmp('D12_G13_M1_A1_T1_firstB_2 navaa_gardaniyeh',        GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D12_G13_M1_A1_T1_firstB_2 navaa_gardaniyeh',        GusheName) == true ) && (i ==9 ))) && ...
            (~((strcmp('D12_G13_M1_A1_T1_firstB_2 navaa_gardaniyeh',        GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D12_G13_M1_A1_T1_lastC_2 navaa_gardaniyeh',         GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D12_G13_M1_A1_T1_lastC_2 navaa_gardaniyeh',         GusheName) == true ) && (i ==9 ))) && ...
            (~((strcmp('D12_G15_M1_A1_T1_firstB_3 navaa_naghmeh',           GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D12_G15_M1_A1_T1_lastC_3 navaa_naghmeh',           GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D12_G23_M1_A1_T1_lastC_5 navaa_oshshaaq',           GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D12_G23_M1_A1_T1_lastC_5 navaa_oshshaaq',           GusheName) == true ) && (i ==11 ))) && ...
            (~((strcmp('D12_G23_M1_A1_T1_firstB_5 navaa_oshshaaq',          GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D12_G23_M1_A1_T1_lastC_5 navaa_oshshaaq',           GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D12_G23_M1_A1_T1_lastC_5 navaa_oshshaaq',           GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D12_G23_M1_A1_T1_firstB_5 navaa_oshshaaq',          GusheName) == true ) && (i ==10))) && ...
            (~((strcmp('D12_G25_M1_A1_T1_firstB_10 navaa_eraaq',            GusheName) == true ) && (i ==15))) && ...
            (~((strcmp('D12_G25_M1_A1_T1_lastC_10 navaa_eraaq',             GusheName) == true ) && (i ==15))) && ...
            (~((strcmp('D12_G42_M1_A1_T1_firstB_7 navaa_xojasteh',            GusheName) == true ) && (i ==9 ))) && ...
            (~((strcmp('D12_G42_M1_A1_T1_lastC_7 navaa_xojasteh',             GusheName) == true ) && (i ==9 ))) && ...
            (~((strcmp('D12_G38_M1_A1_T1_firstB_8 navaa_neyshaburak',         GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D12_G38_M1_A1_T1_lastC_8 navaa_neyshaburak',         GusheName) == true ) && (i ==7 ))) && ...
            (~((strcmp('D12_G43_M1_A1_T1_firstB_9 navaa_hoseyni',             GusheName) == true ) && (i ==14 ))) && ...
            (~((strcmp('D12_G43_M1_A1_T1_lastC_9 navaa_hoseyni',             GusheName) == true ) && (i ==14 ))) && ...
            (~((strcmp('D12_G43_M1_A1_T1_lastC_9 navaa_hoseyni',             GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D12_G43_M1_A1_T1_firstB_9 navaa_hoseyni',             GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_firstB_11 navaa_neyrizOgusheNeyriz',             GusheName) == true ) && (i ==11 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_lastC_11 navaa_neyrizOgusheNeyriz',              GusheName) == true ) && (i ==11 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_lastC_11 navaa_neyrizOgusheNeyriz',              GusheName) == true ) && (i ==9 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_firstB_11 navaa_neyrizOgusheNeyriz',             GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_lastC_11 navaa_neyrizOgusheNeyriz',             GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_firstB_11 navaa_neyrizOgusheNeyriz',             GusheName) == true ) && (i ==19 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_lastC_11 navaa_neyrizOgusheNeyriz',             GusheName) == true ) && (i ==19 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_lastC_11 navaa_neyrizOgusheNeyriz',             GusheName) == true ) && (i ==20 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_firstB_11 navaa_neyrizOgusheNeyriz',             GusheName) == true ) && (i ==25 ))) && ...
            (~((strcmp('D12_G51_M1_A1_T1_lastC_11 navaa_neyrizOgusheNeyriz',             GusheName) == true ) && (i ==25 ))) && ...
            (~((strcmp('D12_G58_M1_A1_T1_lastC_12 navaa_rohabOnaqus',             GusheName) == true ) && (i ==3 ))) && ...
            (~((strcmp('D12_G58_M1_A1_T1_lastC_12 navaa_rohabOnaqus',             GusheName) == true ) && (i ==20 ))) && ...
            (~((strcmp('D12_G63_M1_A1_T1_firstB_13 navaa_taxtTaqdis',             GusheName) == true ) && (i ==1 ))) && ...
            (~((strcmp('D12_G63_M1_A1_T1_lastC_13 navaa_taxtTaqdis',              GusheName) == true ) && (i ==1 ))) && ...
            (~((strcmp('D12_G63_M1_A1_T1_firstB_13 navaa_taxtTaqdis',             GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D12_G63_M1_A1_T1_lastC_13 navaa_taxtTaqdis',              GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D12_G63_M1_A1_T1_firstB_13 navaa_taxtTaqdis',             GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D12_G63_M1_A1_T1_lastC_13 navaa_taxtTaqdis',             GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_firstB_14 navaa_shahXataaii',             GusheName) == true ) && (i ==2 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',              GusheName) == true ) && (i ==2 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_firstB_14 navaa_shahXataaii',             GusheName) == true ) && (i ==4 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_firstB_14 navaa_shahXataaii',             GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',             GusheName) == true ) && (i ==4 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',             GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',             GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',             GusheName) == true ) && (i ==13 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_firstB_14 navaa_shahXataaii',             GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_firstB_14 navaa_shahXataaii',             GusheName) == true ) && (i ==15 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',             GusheName) == true ) && (i ==15 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_firstB_14 navaa_shahXataaii',             GusheName) == true ) && (i ==22 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',             GusheName) == true ) && (i ==22 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_firstB_14 navaa_shahXataaii',             GusheName) == true ) && (i ==27 ))) && ...
            (~((strcmp('D12_G62_M1_A1_T1_lastC_14 navaa_shahXataaii',             GusheName) == true ) && (i ==27 ))) && ...
            (~((strcmp('D13_G3_M1_A1_T1_firstB_1 rast5gaah_daraamad',             GusheName) == true ) && (i ==6 ))) && ...
            (~((strcmp('D13_G3_M1_A1_T1_firstB_1 rast5gaah_daraamad',             GusheName) == true ) && (i ==21 ))) && ...
            (~((strcmp('D13_G3_M1_A1_T1_firstB_1 rast5gaah_daraamad',             GusheName) == true ) && (i ==22 ))) && ...
            (~((strcmp('D13_G3_M1_A1_T1_firstB_1 rast5gaah_daraamad',             GusheName) == true ) && (i ==23 ))) && ...
            (~((strcmp('D13_G26_M1_A1_T1_firstB_3 rast5gaah_naghme',          GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D13_G38_M1_A1_T1_firstB_6 rast5gaah_panjgaahSepehr',  GusheName) == true ) && (i ==11 ))) && ...
            (~((strcmp('D13_G38_M1_A1_T1_firstB_6 rast5gaah_panjgaahSepehr',  GusheName) == true ) && (i ==12 ))) && ...
            (~((strcmp('D13_G44_M1_A1_T1_firstB_7 rast5gaah_oshaaq',          GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D13_G44_M1_A1_T1_firstB_7 rast5gaah_oshaaq',          GusheName) == true ) && (i ==17 ))) && ...
            (~((strcmp('D13_G44_M1_A1_T1_firstB_7 rast5gaah_oshaaq',          GusheName) == true ) && (i ==25 ))) && ...
            (~((strcmp('D13_G60_M1_A1_T1_firstB_9 rast5gaah_nahibMohayyer',   GusheName) == true ) && (i ==21 ))) && ...
            (~((strcmp('D13_G103_M1_A1_T1_firstB_12 rast5gaah_raakHendi',     GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D13_G105_M1_A1_T1_firstB_14 rast5gaah_raakKeshmir',   GusheName) == true ) && (i ==1 ))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_firstB_5 Shur_owj',                  GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_lastC_5 Shur_owj',                   GusheName) == true ) && (i ==5 ))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_firstB_5 Shur_owj',                  GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_lastC_5 Shur_owj',                  GusheName) == true ) && (i ==8 ))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_lastC_5 Shur_owj',                   GusheName) == true ) && (i ==10 ))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_firstB_5 Shur_owj',                  GusheName) == true ) && (i ==13))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_lastC_5 Shur_owj',                   GusheName) == true ) && (i ==13))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_firstB_5 Shur_owj',                   GusheName) == true ) && (i ==15))) && ...
            (~((strcmp('D1_G100_M1_A1_T1_lastC_5 Shur_owj',                   GusheName) == true ) && (i ==15))) && ...
            (~((strcmp('D1_G154_M1_A1_T1_lastC_15 Shur_masnavi',              GusheName) == true ) && (i ==10+notYet))) && ...
            (~((strcmp('D1_G154_M1_A1_T1_lastC_15 Shur_masnavi',              GusheName) == true ) && (i ==2))) && ...
            (~((strcmp('D1_G154_M1_A1_T1_firstB_15 Shur_masnavi',             GusheName) == true ) && (i ==2))) && ...
            (~((strcmp('D1_G46_M1_A1_T1_firstB_13 Shur_zirkash_salmak',       GusheName) == true ) && (i ==7))) && ...
            (~((strcmp('D1_G46_M1_A1_T1_firstB_13 Shur_zirkash_salmak',       GusheName) == true ) && (i ==14))) && ...
            (~((strcmp('D1_G46_M1_A1_T1_lastC_13 Shur_zirkash_salmak',        GusheName) == true ) && (i ==7))) && ...
            (~((strcmp('D1_G46_M1_A1_T1_lastC_13 Shur_zirkash_salmak',        GusheName) == true ) && (i ==14))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==22))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==27))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==26))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_firstB_14 Shur_gusheh_grayli(daraamad_grayli)',GusheName) == true ) && (i ==26))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==28))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==29+notYet))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==30))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==32))) && ...
            (~((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==34))) && ...
            (~((strcmp('D1_G123_M1_A1_T1_firstB_6 Shur_shahnaaz',   GusheName) == true ) && (i ==7))) && ...
            (~((strcmp('D1_G123_M1_A1_T1_firstB_6 Shur_shahnaaz',   GusheName) == true ) && (i ==12))) && ...
            (~((strcmp('D1_G131_M1_A1_T1_firstB_7 Shur_qaracheh',   GusheName) == true ) && (i ==4))) && ...
            (~((strcmp('D1_G131_M1_A1_T1_lastC_7 Shur_qaracheh',    GusheName) == true ) && (i ==4))) && ...
            (~((strcmp('D1_G7_M1_A1_T1_firstB_3 Shur_daraamad_xaaraa',GusheName) == true ) && (i ==11))) && ...
            (~((strcmp('D1_G7_M1_A1_T1_lastC_3 Shur_daraamad_xaaraa',GusheName) == true ) && (i ==11))) && ...
            (~((strcmp('D1_G20_M1_A1_T1_firstB_2 Shur_kereshmeh',   GusheName) == true ) && (i ==4))) && ...
            (~((strcmp('D1_G20_M1_A1_T1_lastC_2 Shur_kereshmeh',    GusheName) == true ) && (i ==4))) && ...
            (~((strcmp('D1_G76_M1_A1_T1_firstB_10 Shur_bozorg',     GusheName) == true ) && (i ==11))) && ...
            (~((strcmp('D1_G76_M1_A1_T1_lastC_10 Shur_bozorg',      GusheName) == true ) && (i ==11))) && ...
            (~((strcmp('D1_G117_M1_A1_T1_lastC_9 Shur_razavi_baa_tahrir_javaadxaani',  GusheName) == true ) && (i ==11))) && ...
            (~((strcmp('D1_G117_M1_A1_T1_firstB_9 Shur_razavi_baa_tahrir_javaadxaani', GusheName) == true ) && (i ==11))) && ...
            (~((strcmp('D1_G117_M1_A1_T1_lastC_9 Shur_razavi_baa_tahrir_javaadxaani',  GusheName) == true ) && (i ==16))) && ...
            (~((strcmp('D1_G117_M1_A1_T1_firstB_9 Shur_razavi_baa_tahrir_javaadxaani', GusheName) == true ) && (i ==16))) && ...
            (~((strcmp('D1_G77_M1_A1_T1_lastC_11 Shur_dobeyti',     GusheName) == true ) && (i ==7))) && ...
            (~((strcmp('D1_G77_M1_A1_T1_lastC_11 Shur_dobeyti',     GusheName) == true ) && (i ==8))) && ...
            (~((strcmp('D1_G77_M1_A1_T1_lastC_11 Shur_dobeyti',     GusheName) == true ) && (i ==9))) && ...
            (~((strcmp('D1_G77_M1_A1_T1_firstB_11 Shur_dobeyti',    GusheName) == true ) && (i ==9))) && ...
            (~((strcmp('D1_G147_M1_A1_T1_firstB_12 Shur_hoseyni',   GusheName) == true ) && (i ==17))) && ...
            (~((strcmp('D1_G147_M1_A1_T1_lastC_12 Shur_hoseyni',    GusheName) == true ) && (i ==17))) && ...
            (~((strcmp('D4_G5_M1_A1_T1_lastC_1 afshaari_daraamad',  GusheName) == true ) && (i ==19))) && ...
            (~((strcmp('D4_G26_M1_A1_T1_lastC_2 afshaari_jaamehdaraan',   GusheName) == true ) && (i == 9)))    &&...
            (~((strcmp('D4_G26_M4_A7_T3_firstB_2 afshaari_jaamehdaraandavaami',   GusheName) == true ) && (9 == 9)))    &&...
            (~((strcmp('D4_G28_M1_A1_T1_lastC_3 afshaari_hesaar',   GusheName) == true ) && (i == 5)))    &&...
            (~((strcmp('D4_G28_M1_A1_T1_firstB_3 afshaari_hesaar',  GusheName) == true ) && (i == 5)))    &&...
            (~((strcmp('D4_G28_M1_A1_T1_lastC_3 afshaari_hesaar',   GusheName) == true ) && (i ==12)))    &&...
            (~((strcmp('D4_G32_M1_A1_T1_lastC_4 afshaari_qaraaii',  GusheName) == true ) && (i ==15)))  && ...
            (~((strcmp('D4_G39_M1_A1_T1_lastC_5 afshaari_nahib',    GusheName) == true ) && (i == 8)))  && ...
            (~((strcmp('D4_G39_M1_A1_T1_firstB_5 afshaari_nahib',   GusheName) == true ) && (i == 8))) && ...
            (~((strcmp('D4_G42_M1_A1_T1_lastC_6 afshaari_hazin',    GusheName) == true ) && (i == 3))) && ...
            (~((strcmp('D4_G57_M1_A1_T1_lastC_9 afshaari_masnavi',  GusheName) == true ) && (i ==10))) && ...
            (~((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==10)))&& ...
            (~((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==16)))&& ...
            (~((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==12)))&& ...
            (~((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==13)))&& ...
            (~((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==16)))&& ...
            (~((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==17)))&& ...
            (~((strcmp('D4_G57_M1_A1_T1_lastC_9 afshaari_masnavi',  GusheName) == true ) && (i ==12)))&& ...
            (~((strcmp('D4_G57_M1_A1_T1_firstB_9 afshaari_masnavi', GusheName) == true ) && (i ==23)))&& ...
            (~((strcmp('D4_G57_M1_A1_T1_lastC_9 afshaari_masnavi',  GusheName) == true ) && (i ==23)))&& ...
            (~((strcmp('D4_G56_M1_A1_T1_firstB_8 afshaari_sadri',   GusheName) == true ) && (i ==10)))&& ...
            (~((strcmp('D4_G56_M1_A1_T1_lastC_8 afshaari_sadri',    GusheName) == true ) && (i ==10)))&& ...
            (~((strcmp('D4_G56_M1_A1_T1_lastC_8 afshaari_sadri',    GusheName) == true ) && (i ==11)))&& ...
            (~((strcmp('D4_G56_M1_A1_T1_firstB_8 afshaari_sadri',    GusheName) == true) && (i ==11)))&& ...
            (~((strcmp('D4_G44_M1_A1_T1_firstB_7 afshaari_rohaab',  GusheName) == true ) && (i ==15)))&& ...
            (~((strcmp('D4_G44_M1_A1_T1_lastC_7 afshaari_rohaab',  GusheName) == true  ) && (i ==15)))&& ...
            (~((strcmp('D4_G44_M1_A1_T1_firstB_7 afshaari_rohaab',   GusheName) == true)  && (i ==13))) && ...
            (~((strcmp('D4_G44_M1_A1_T1_lastC_7 afshaari_rohaab',   GusheName) == true ) && (i ==13)))   ...
            )
        
        fprintf("++********************************************************i = %d  >%s\n", i, GusheName);
        
        fprintf("++splitplot1: notYet =%d  curve size = %d  segs=%d\n",notYet,  seg(i).curveEnd-seg(i).curveBeg , size(seg,2));
        fprintf("\t\t\t\t\t i=%d, raw=%d Beg = %d end=  %d zero=    %d ", i, ix(seg(i).curveBeg),seg(i).curveBeg, seg(i).curveEnd, seg(i).zeroEnd);
        fprintf("\t&\t\t\t i=%d, raw=%d Beg = %d end=  %d zero=    %d \n", i, ix(seg(i+1).curveBeg),seg(i+1).curveBeg, seg(i+1).curveEnd, seg(i+1).zeroEnd);
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd = seg(i+1).zeroEnd;
        inc =0;
        seg = [seg(1:i) seg(i+2:end) ];
        if (strcmp('D1_G154_M1_A1_T1_lastC_15 Shur_masnavi', GusheName) == true ) && (i ==10) ||...
                ((strcmp('D1_G20_M4_A7_T3_firstB_3 shur_Kereshmehdavaami', GusheName) == true ) && (i ==3))
            notYet=0;  % next time, do not connect two segments.
            fprintf("splitplot: i=10\n");
        end
    elseif ((strcmp('D1_G110_M1_A1_T1_lastC_14 Shur_gusheh_grayli(daraamad_grayli)', GusheName) == true ) && (i ==29)) ||...
            ((strcmp('D1_G20_M4_A7_T3_firstB_3 shur_Kereshmehdavaami', GusheName) == true ) && (i ==3)) %%may be not needed
        notYet=0;  % next time, do not connect two segments.
        
        
    end
    if (  (doIt==4) )
        fprintf("++splitplot2: curve size = %d  segs=%d\n", seg(i).curveEnd-seg(i).curveBeg , size(seg,2));
        fprintf("\t\t\t\t\t i=%d,raw=%d  Beg end zero = %d  %d --> %d  zero=%d\n", i, ix(seg(i).curveBeg),...
            seg(i).curveBeg, seg(i).curveEnd, seg(i+1).curveEnd, seg(i).zeroEnd);
        seg(i).curveEnd = seg(i+1).curveEnd;
        seg(i).zeroEnd = seg(i+1).zeroEnd;
        inc=0;
        seg = [seg(1:i) seg(i+2:end) ];
    end
    i = i + inc;
end
fprintf("\n\n");
for z=1:size(seg,2)
    fprintf("++segs B:%d raw=%d  beg end zero= %d  %d  %d   (%d)\n",z, ix(seg(z).curveBeg), seg(z).curveBeg, seg(z).curveEnd, seg(z).zeroEnd, seg(z).curveEnd-seg(z).curveBeg );
end
for i=2:size(seg,2)
    ii=1;
    while (y_cent(ix(seg(i).curveBeg-1))== 0) &&...
            (ii<50 )  && (ix(seg(i).curveBeg)< size(y_cent,1))
        seg(i).curveBeg = seg(i).curveBeg - 1;
        ii = ii + 1;
    end
    ii = 1;
    while ( (ix(seg(i).curveEnd)< size(y_cent,1)) && ...
            y_cent(ix(seg(i).curveEnd+1))== 0) && (ii<30)
        seg(i).curveEnd = seg(i).curveEnd + 1;
        
        ii = ii + 1;
    end
    if ( ii <3) && (i ~= size(seg,2) )
        figure
        plot( y_cent);
        title("problematic curve????");
        pause(5);
        error( "++splitplot: ..ii < 3");
    end
end
for z=1:size(seg,2)
    fprintf("++segs C:%d raw=%d  beg end zero= %d  %d  %d     (%d)\n",z, ...
        ix(seg(z).curveBeg),seg(z).curveBeg, seg(z).curveEnd, seg(z).zeroEnd,seg(z).curveEnd -seg(z).curveBeg );
end
fprintf("++starting print loop ****************************************************\n");
name=regexprep(GusheName,"firstB","firstB_dtw");
name=regexprep(name,"lastC","lastC_dtw");

print(fig, strcat(name,"_full.jpg"),'-djpeg' );
for i=1:size(seg,2)
    %pause(3);
    %fprintf("xlim change   i=%d\n", i);
    xlim([seg(i).curveBeg seg(i).curveEnd])
    min = 10000;
    max = 0;
    for d = seg(i).curveBeg:seg(i).curveEnd
        if (y_cent( ix(d)) > max)
            max = y_cent(ix(d));
        end
        if (MidiFreq(iy(d)) > max)
            max = MidiFreq(iy(d));
        end
        
        if ( y_cent(ix(d)) ~= 0) && (y_cent( ix(d)) <min )
            min = y_cent(ix(d));
            if min <200
                error("++why so low?=  %d,   %d", min, ix(d));
            end
        end
        if (MidiFreq(iy(d)) >50 ) && (MidiFreq(iy(d)) < min)
            min = MidiFreq(iy(d));
            if min <200
                error("++why so low?=%d", min);
            end
        end
    end
    if min <200
        error("++why so low?=%d", min);
    end
    if min >1100
        min = 1100;
    end
    ylim([min-30 max+20]);
    partFilename= sprintf("%s_part%d.jpg",name, i);
    print(fig, partFilename,'-djpeg' );  %, '-fillpage'  to remove margins. hope it works -sh
end

xlim([1 size(ix,1)]);
ylim([1 4000]);
end