%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) copyright 2021 Sepideh Shafiei (sepideh.shafiee@gmail.com), all rights reserved
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

NoteNamesFigure={' C ','Cs ','Db ','Dk '....
    ' D ','Ds ','Eb ','Ek '....
    ' E ','Fk ',....
    ' F ','Fs ','F# ','Gk '....
    ' G ','Gs ','Ab ','Ak '....
    ' A ','As ','Bb ','Bk '....
    ' B ','Bs ',...
    ' C ','Cs ','Db ','Dk '....
    ' D ','Ds ','Eb ','Ek '....
    ' E ','Fk ',....
    ' F ','Fs ','F# ','Gk '....
    ' G ','Gs ','Ab ','Ak '....
    ' A ','As ','Bb ','Bk '....
    ' B ','Bs ',...
    ' C ','Cs ','Db ','Dk '....
    ' D ','Ds ','Eb ','Ek '....
    ' E ','Fk ',....
    ' F ','Fs ','F# ','Gk '....
    ' G ','Gs ','Ab ','Ak '....
    ' A ','As ','Bb ','Bk '....
    ' B ','Bs ',...
    ' C ','Cs ','Db ','Dk '....
    ' D ','Ds ','Eb ','Ek '....
    ' E ','Fk ',....
    ' F ','Fs ','F# ','Gk '....
    ' G ','Gs ','Ab ','Ak '....
    ' A ','As ','Bb ','Bk '....
    ' B ','Bs ',...
    };

NoteNamesFigure2={' C ',' D ', ' E ',' F ',' G ',....
    ' A ' ' B ',  ' C ',' D ', ' E ',' F ',' G ',....
    ' A ',' B ',  ' C ',' D ', ' E ',' F ',' G ',....
    ' A ',' B ',  ' C ',' D ', ' E ',' F ',' G ',....
    ' A ',' B ',...
    };

NoteNames={' C','Cs','Db','Dk'....
    ' D','Ds','Eb','Ek'....
    ' E','Fk',....
    ' F','Fs','F#','Gk'....
    ' G','Gs','Ab','Ak'....
    ' A','As','Bb','Bk'....
    ' B','Bs',...
    };
